on: push

env:
  AWS_EC2_PEM: ${{secrets.AWS_EC2_PEM}}
jobs:
  job1:
    runs-on: ubuntu-latest
    # if: false # this is to disable the job

    steps:
      # - name: Checkout
      # uses: actions/checkout@v2

      - name: Ops
        env:
          MY_CITY: "Lagos"
        run: |
          echo "My awesome env vars are: ${{env.MY_CITY}} & ${{env.AWS_EC2_PEM}}"
