on: push

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::553917154144:role/s3-full-access-role
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: s3 upload
        run: aws s3 cp index.html "s3://zeelz-bucket-from-cli"
