on: push

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: just checking
        run: |
          echo "AWS version"
          aws --version
