on:
    # workflow_call:
    workflow_run:
        workflows: ["Rialto API Test"]
        types:
            - completed

jobs:
    slack-notification:
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}  # Trigger only on failure
        runs-on: ubuntu-latest

        steps:
            - name: send slack-notification
              env:
                MEMBER_IDS: ${{ vars.MEMBER_IDS }}
              run: |
                MEMBER_ID=$(echo $MEMBER_IDS | jq -r ".${{ github.actor }}")

                PR_TITLE="${{ github.event.pull_request.title }}"

                JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

                NOTIF_TEXT="Some \`test\` checks for the pull request _*$PR_TITLE*_ were not successful.\nSee $JOB_URL\nActor involved <@$MEMBER_ID>"
                
                curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"$NOTIF_TEXT\"}" ${{ secrets.SLACK_APP_WEBHOOK_URL }}