name: "Rialto API Test"

on:
    push:
    pull_request:

jobs:
    test-api:
        runs-on: ubuntu-latest
        steps:
            # - name: checkout
            #   uses: "actions/checkout@v4"

            # - name: node setup
            #   uses: "actions/setup-node@v3"

            # - name: install packages
            #   run: npm i

            # - name: test
            #   run: npm run test
            - run: cd $NON_EXISTENT

    # slack-notification:
    #     if: failure()
    #     uses: ./.github/workflows/slack-notification.yml
