on:
    push

jobs:
    test-api:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: "actions/checkout@v4"

            - name: node setup
              uses: "actions/setup-node@v3"

            - name: install packages
              run: npm i

            - name: test
              run: npm run test

            - name: if test fails
              if: failure()
              run: |
                echo "Run ID: ${{ github.run_id}}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Repo ${{ github.repository }}"
                echo "Trigger: ${{ github.event_name }}"
                echo "Actor/PR Creator: ${{ github.actor }}"
                curl -X POST -H "Content-Type application/json" -d '{"text": "test failed - ${{ github.run_id }}"}' ${{ secrets.SLACK_APP_WEBHOOK_URL }}