on:
    push

jobs:
    test-api:
        runs-on: ubuntu-latest

        steps:
            # - name: checkout
            #   uses: "actions/checkout@v4"

            # - name: node setup
            #   uses: "actions/setup-node@v3"

            # - name: install packages
            #   run: npm i

            # - name: test
            #   run: npm run test

            - name: if test fails
              run: |
                echo ${{ github.job }}
                switch_case() {
                    local value="$1"

                    case "$value" in
                        "apple")
                            echo "Fruit"
                            ;;
                        "car")
                            echo "Vehicle"
                            ;;
                        "blue")
                            echo "Color"
                            ;;
                        *)
                            echo "Unknown"
                            return 1
                            ;;
                    esac
                }

                # Usage example
                MEMBER_ID=vancouver #switch_case "apple" 
                NOTIF_TEXT="Some test checks for the pull request $MEMBER_ID"
                echo $NOTIF_TEXT
                
                #*Add test workflow* were not successful\nSee https://github.com/zeelz/github-action/actions/runs/12010559857/job/33477660383?pr=4\nActor involved @Uche"
                # curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"$NOTIF_TEXT\"}" ${{ secrets.SLACK_APP_WEBHOOK_URL }}