on:
    push

jobs:
    test-api:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: "actions/checkout@v4"

            - name: node setup
              uses: "actions/setup-node@v3"

            - name: install packages
              run: npm i

            - name: test
              run: npm run test

            - name: if test fails
              if: failure()
              run: |
                curl -X POST -d "{\"text\": \"test failed\"}" https://hooks.slack.com/services/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
